# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d4b853d340911cfdfc959123e65a2c7638340572e750b932a6dc4b24cdb69fcb94fac17423bafc9272232b9d006fdca046679ba852982107aa37265de4e5b8
  stripe_publishable_key: pk_test_DxbtXsZyRjhTJKBO9WJ3o82t
  stripe_secret_key: sk_test_L79je7rK8GJLQnvT5KMeQ9fX

test:
  secret_key_base: 6f6f6f9e85dcf14bae31e601c45017621e9003108260258dcd0a05c10f8ee2166f310f9091e62e4baf0c0315b626bcbba6c21831e44cb1bca733f36565acf25f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
