source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails', '4.2.2'

gem 'rails-api'

gem 'spring', :group => :development

gem 'rake', '11.1.1'

gem 'pg'

gem 'active_model_serializers'
gem 'devise'
gem 'jwt'
gem 'rack-cors', :require => 'rack/cors'

gem 'twitter', '~> 5.15'
gem 'tumblr_client', '~> 0.8.5'
gem "koala", "~> 2.2"
gem 'postmark'
gem 'merit'
# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
